app/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.SignupPage,name='signup'),
    path('login/',views.LoginPage,name='login'),
    path('home/',views.HomePage,name='home'),
    path('logout/',views.LogoutPage,name='logout'),
    path('share/',views.Sharepage,name='share'),
    path('user-media/uploads/<uuid:unique_link>',views.access_shared_file, name='access_shared_file'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),
]

file_manager/urls.py
from django.contrib import admin
from django.urls import path,include
from app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('app.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from .models import File,Comment
from django_select2.forms import Select2Widget
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox

# Create the form class.
class FileForm(ModelForm,forms.Form):
    # shared_with = forms.ModelMultipleChoiceField(
    #     queryset=User.objects.all(),
    #     widget=forms.Select(),
    #     required=False
    # )
    class Meta: 
        model = File
        fields = ["file"]



class Userform(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}),required=True,)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password'}),required=True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Valid Email only'}), required=True)
    class Meta: 
        model = get_user_model()
        fields = ['username']
    def save(self, commit=True):
        user = super(Userform, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class Commentform(ModelForm):
    class Meta:
        model=Comment
        fields=['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 1, 'cols': 30}),
        }

class ShareForm(forms.Form):
    shared_with=forms.ModelChoiceField(queryset=User.objects.all(),widget=Select2Widget,empty_label='Select a user',)
    shared_file=forms.ModelChoiceField(queryset=File.objects.all(),to_field_name='filename',widget=Select2Widget,empty_label='Select a File',)
    def __init__(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)
        super(ShareForm, self).__init__(*args, **kwargs)
        if current_user:
            self.fields['shared_with'].queryset = User.objects.exclude(username=current_user.username)
            user_id=User.objects.get(username=current_user.username).id
            queryset1 = File.objects.filter(display_name=user_id)  # First queryset
            queryset2 = File.objects.filter(shared_with=user_id)   # Second queryset
            combined_queryset = queryset1.union(queryset2)     # Combine the two querysets
            self.fields['shared_file'].queryset = combined_queryset


class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

templates/access_shared_file.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>PDF Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        body {
            background-color: #F0F2F5;
            font-family: Arial, sans-serif;
        }

        .container {
            border: 2px solid grey;
            border-radius: 8px;
            margin: 5vh auto;
            padding: 3vh 4vw;
        }

        .container>div {
            text-align: center;
            padding: 0 20px;
        }

        .content-section {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);
        }

        .custom-link {
            background-color: #007BFF;
            color: #FFFFFF;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            text-decoration: none;
            padding: 8px 16px;
            transition: background-color 0.3s ease;
        }

        .custom-link:hover {
            background-color: #0056b3;
        }

        .comment-section {
            margin-top: 20px;
        }

        .comment {
            background-color: #F8F9FA;
            border: 1px solid #E9ECEF;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
        }

        .button-ty {
            margin-top: 10px;
        }

        textarea {
            width: 100%;
            height: 75px;
            resize: none;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #CCCCCC;
            border-radius: 5px;
            background-color: #F8F9FA;
            outline: none;
            transition: border-color 0.3s ease;
        }

        textarea:focus {
            border-color: #007BFF;
        }
    </style>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div>
            <h4>Uploaded by: {{ file.display_name }}</h4>
            <label for="">File : </label><a href="{{ file.file.url }}" target="_blank"
                class=" btn btn-primary custom-link">{{file.filename}}</a>
        </div>
        <h3>Comments:</h3>
        {% for comment in comments %}
        <p>{{ comment.user.username }}: {{ comment.content }}</p>
        {% endfor %}
        <form action=" {% url 'access_shared_file' file.unique_link%}" method="POST">
            {% csrf_token %}
            {{form.content}}
            <br>
            <button type="submit" class="btn btn-primary button-ty">Comment</button>
        </form>
    </div>
    {% include 'footer.html' %}

    <script>
        // JavaScript code
        window.addEventListener("unload", function () {
            // Perform an AJAX request to log out the user
            var xhr = new XMLHttpRequest();
            xhr.open("POST", "/logout/");  // Replace "/logout/" with your logout URL

            // Include the CSRF token as a header
            xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
            xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));  // Include the CSRF token as a header

            xhr.onload = function () {
                // Handle the response if needed
            };

            xhr.send();
        });

        // Function to retrieve the CSRF token from the cookie
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== "") {
                var cookies = document.cookie.split(";");

                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === name + "=") {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

</body>

</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>error</title>
</head>

<body>
  {{error}}
  <a href="{% url 'login' %}" target="_self" class="btn btn-primary">login</a>
  <a href="{% url 'signup' %}" target="_self" class="btn btn-primary">signup</a>
  <script>
    // JavaScript code
    window.addEventListener("unload", function () {
      // Perform an AJAX request to log out the user
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "/logout/");  // Replace "/logout/" with your logout URL

      // Include the CSRF token as a header
      xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
      xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));  // Include the CSRF token as a header

      xhr.onload = function () {
        // Handle the response if needed
      };

      xhr.send();
    });

    // Function to retrieve the CSRF token from the cookie
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        var cookies = document.cookie.split(";");

        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
  </script>
</body>

</html>

templates/footer.html
<style>
    footer {
        background-color: #343a40;
        height: 10%;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        position: absolute;
        width: 100vw;
        bottom: 0;
    }

    .footer-links {
        margin: 30px 10px;
    }

    .links {
        text-decoration: none;
        color: gray;
        margin: 0 30px;
    }

    .links:hover {
        text-decoration: none;
        color: white;
    }

    footer>p {
        color: gray;
    }
</style>
<footer>
    <div class="footer-links">
        <a class="links" href="mailto:jitendrasingh28321155@gmail.com" target="_blank">Mail</a>
        <a class="links" href="https://github.com/Jitendra2584" target="_blank" rel="noopener noreferrer">Github</a>
        <a class="links" href="https://www.linkedin.com/in/jitendra-singh-4173b0244/" target="_blank"
            rel="noopener noreferrer">LinkedIn</a>
    </div>
    <!-- <p class="copyright">© Copyright 2023 - File Manager</p> -->
</footer>

templates/home.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Home Page</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      background: #EFEFEF;
    }

    form {
      border: 2px solid grey;
      border-radius: 8px;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      margin: 50px;
      padding: 20px 0;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    input {
      width: 205px;
    }

    .files__manager {
      display: flex;
      justify-content: space-between;
      padding: 100px;
    }

    .files__button {
      margin: 2px;
    }

    .files__manager__container>h3 {
      text-decoration: underline grey 1.5px;
    }

    .files__manager__container {
      padding: 4%;
      border: 2px solid grey;
      border-radius: 8px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }
  </style>
</head>

<body>

  {% include 'navbar.html' %}
  {% if errors %}
  <br>
  <h2>{{errors}}</h2>
  {% endif %}
  <div class="container">
    <form action="/home/" method="POST" enctype="multipart/form-data" class="form">
      {% csrf_token %}
      <label>Click on the "Choose File" button to upload a file:</label> {{form.file}}
      <p>Only PDF allowed</p>
      <button type="submit" class="btn btn-dark">Upload</button>
      <!-- <input type="file" name="pdf">  -->
    </form>
    <div class="files__manager">
      <div class="files__manager__container">
        <h3>Files Uploaded by You</h3>
        <ol>
          {% for file in files %}
          <li>
            <a href="{% url 'access_shared_file' file.unique_link%}" target="_self"
              class="btn btn-dark custom-link files__button">{{file.filename}}</a>
          </li>
          {% empty %}
          <li>No Files Uploaded Yet.</li>
          {% endfor %}
        </ol>
      </div>
      <div class="files__manager__container">
        <h3>Files Shared to You</h3>
        <ol>
          {% for file in shared_files %}
          <li>
            <a href="{% url 'access_shared_file' file.unique_link%}" target="_self"
              class="btn btn-dark custom-link">{{file.filename}}</a><br>
          </li>
          {% empty %}
          <li>No files shared to you yet.</li>
          {% endfor %}
        </ol>
      </div>
    </div>
  </div>
  {% include 'footer.html' %}
  <script>
    // JavaScript code
    window.addEventListener("unload", function () {
      // Perform an AJAX request to log out the user
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "/logout/");  // Replace "/logout/" with your logout URL

      // Include the CSRF token as a header
      xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
      xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));  // Include the CSRF token as a header

      xhr.onload = function () {
        // Handle the response if needed
      };

      xhr.send();
    });

    // Function to retrieve the CSRF token from the cookie
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        var cookies = document.cookie.split(";");

        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
  </script>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Design by foolishdeveloper.com -->
    <title>Login Page</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
        *,
        *:before,
        *:after {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        body {
            background-color: #080710;
            color: white;
        }

        .background {
            width: 430px;
            height: 520px;
            position: absolute;
            transform: translate(-50%, -50%);
            left: 50%;
            top: 50%;
        }

        .background .shape {
            height: 200px;
            width: 200px;
            position: absolute;
            border-radius: 50%;
        }

        .shape:first-child {
            background: linear-gradient(#1845ad,
                    #23a2f6);
            left: -80px;
            top: -80px;
        }

        .shape:last-child {
            background: linear-gradient(to right,
                    #ff512f,
                    #f09819);
            right: -30px;
            bottom: -80px;
        }

        form {
            height: 520px;
            width: 400px;
            background-color: rgba(255, 255, 255, 0.13);
            position: absolute;
            transform: translate(-50%, -50%);
            top: 50%;
            left: 50%;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
            padding: 50px 35px;
        }

        form * {
            font-family: 'Poppins', sans-serif;
            color: #ffffff;
            letter-spacing: 0.5px;
            outline: none;
            border: none;
        }

        form h3 {
            font-size: 32px;
            font-weight: 500;
            line-height: 42px;
            text-align: center;
        }

        label {
            display: block;
            margin-top: 30px;
            font-size: 16px;
            font-weight: 500;
        }

        input {
            display: block;
            height: 50px;
            width: 100%;
            background-color: rgba(255, 255, 255, 0.07);
            border-radius: 3px;
            padding: 0 10px;
            margin-top: 8px;
            font-size: 14px;
            font-weight: 300;
        }

        ::placeholder {
            color: #e5e5e5;
        }

        button {
            margin-top: 50px;
            width: 100%;
            background-color: #ffffff;
            color: #080710;
            padding: 15px 0;
            font-size: 18px;
            font-weight: 600;
            border-radius: 5px;
            cursor: pointer;
        }

        .social {
            margin-top: 30px;
            display: flex;
        }

        .social div {
            background: red;
            width: 150px;
            border-radius: 3px;
            padding: 5px 10px 10px 5px;
            background-color: rgba(255, 255, 255, 0.27);
            color: #eaf0fb;
            text-align: center;
        }

        .social div:hover {
            background-color: rgba(255, 255, 255, 0.47);
        }

        .social .fb {
            margin-left: 25px;
        }

        .social i {
            margin-right: 4px;
        }
    </style>
</head>

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>

    {% if errors %}
    <br>
    <h2>{{errors}}</h2>
    {% endif %}
    <form method="post" action="/login/">
        {% csrf_token %}
        <h3>Login Here</h3>
        <label for="username">Username</label>
        <input type="text" placeholder="Enter Username" id="username" name="username" required>

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password" name="pass" required>

        <button type="submit">Log In</button>
        <a href="{% url 'signup' %}">Create a account</a><br>
        <a href="{% url 'password_reset' %}">Forget Password</a>
        <!-- <input type="button" value=""> -->
        <!-- <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div> -->
    </form>

</body>

</html>

templates/navbar.html
<style>
    .navbar {
        position: sticky;
        top: 0;
        z-index: 100;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand ml-5" href="{% url 'home' %}">File Manager</a>
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse mr-5" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'share' %}">Share File</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'password_change' %}">Change Password</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/password_reset.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body {
      background-color: #F0F2F5;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      flex-direction: column;
    }

    .content-section {
      max-width: 600px;
      padding: 20px;
      background-color: #FFFFFF;
      border-radius: 8px;
      box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);
    }

    .form-group {
      margin-bottom: 20px;
    }

    .content-section>h2 {
      text-align: center;
    }
  </style>
  <title>Home Page</title>
</head>

<body>
  <div class="content-section">
    <h2 class="mb-4">Reset Password</h2>
    <hr>
    <p class="mb-4">Forgotten your password? Enter your email address below, and we'll email instructions for setting a
      new one.</p>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-primary custom-link" type="submit">Send email</button>
      <a href="{% url 'login' %}" class="btn btn-outline-info custom-link" >login</a>
    </form>
  </div>
  {% if errors %}
  <br>
  <h3>{{errors}}</h3>
  {% endif %}


</body>

</html>

templates/password_reset_confirm.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      background-color: #EFEFEF;
    }

    .container {
      border: 2px solid grey;
      border-radius: 8px;
      margin: 5% auto;
      padding: 5%;
    }

    .container>h2 {
      text-align: center;
    }
  </style>
  <title>Change Password</title>
</head>

<body>
  {% include 'navbar.html' %}
  <div class="content-section container">
    <h2>Change Your Password</h2>
    <hr>
    <p>Enter new password and repeat it</p>
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-outline-danger custom-link" type="submit">Change Password</button>
    </form>
  </div>
  {% include 'footer.html' %}

  {% if errors %}
  <br>

  <h3>{{errors}}</h3>
  {% endif %}


</body>

</html>

templates/share.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Share File</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet">
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    body {
      background-color: #EFEFEF;
    }

    .container {
      border: 2px solid grey;
      border-radius: 8px;
      margin: 5% auto;
      padding: 5%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }

    select {
      appearance: none;
      padding: 6px;
      font-size: 16px;
      border: 2px solid #DADADA;
      border-radius: 5px;
      background-color: #F8F8F8;
      color: #333333;
      width: 200px;
    }

    select::after {
      content: "\25BC";
      position: absolute;
      right: 12px;
      top: 50%;
      transform: translateY(-50%);
      pointer-events: none;
    }


    select:focus {
      outline: none;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
    }

    label {
      font-size: x-large;
      margin-bottom: 0;
    }
  </style>
</head>

<body>
  {% include 'navbar.html' %}
  <form action="/share/" method="POST" class="container">
    {% csrf_token %}
    <label for="">Choose a User you want to share file with:</label><br>{{form.shared_with}}<br>
    <label for="">Choose a File you want share: </label><br>{{form.shared_file}}<br>
    <!-- {{form.shared_with}} -->
    <button type="submit" class="btn btn-dark">Share</button>
    <!-- <input type="file" name="pdf">  -->
  </form>
  {% include 'footer.html' %}

  <script>
    // JavaScript code
    window.addEventListener("unload", function () {
      // Perform an AJAX request to log out the user
      var xhr = new XMLHttpRequest();
      xhr.open("POST", "/logout/");  // Replace "/logout/" with your logout URL

      // Include the CSRF token as a header
      xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
      xhr.setRequestHeader("X-CSRFToken", getCookie("csrftoken"));  // Include the CSRF token as a header

      xhr.onload = function () {
        // Handle the response if needed
      };

      xhr.send();
    });

    // Function to retrieve the CSRF token from the cookie
    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        var cookies = document.cookie.split(";");

        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
  <script>
    $(document).ready(function () {
      $('#id_shared_file').select2();
    });
  </script>
  <script>
    $(document).ready(function () {
      $('#id_shared_with').select2();
    });
  </script>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

</body>

</html>

templates/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/template_reset_password.html
{% autoescape off %}
Hello {{ user.username }},

We received a request to reset the password for your account for this email address. To initiate the password reset
process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and
request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
PyLessons

{% endautoescape %}